apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: cv-project/devops
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.targetServer }}
    namespace: {{ .Values.targetNamespace }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true