apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory # this will be set to the project name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: inventory/devops
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.targetServer }}
    namespace: {{ .Values.targetNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true