apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messages # Updated name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }} #Templated repo URL
    path: messages/devops
    targetRevision: {{ .Values.targetRevision }} # Templated target revision
  destination:
    server: {{ .Values.targetServer }}
    namespace: {{ .Values.targetNamespace }} # Templated destination namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true