apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio 
  namespace: argocd 
spec:
  project: default 
  source:
    repoURL: {{ .Values.repoUrl }} 
    path: portfolio/devops 
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.targetServer }}
    namespace: {{ .Values.targetNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true