apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tictactoe  
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: tictactoe/devops
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.targetServer }}
    namespace: {{ .Values.targetNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true