apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
      - name: messages
        image: ghcr.io/smiggiddy/odin-codeprojects/messages:latest
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: production
          # add any other needed environment variables here
---
apiVersion: v1
kind: Service
metadata:
  name: messages-service
spec:
  selector:
    app: messages
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000