name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [admin-dashboard, auth-expressjs, battleship, calculator, cv, cv-project, inventory, library, messages, nodejs-mini-message-board, portfolio, restaurant, shopping-cart, signup_form, tictactoe, todo, weather]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set target revision
        id: set-revision
        run: |
          echo "target_revision=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for existing image
        id: check-image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:${{ steps.set-revision.outputs.target_revision }}
          if docker manifest inspect $IMAGE_NAME > /dev/null 2>&1; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        if: steps.check-image.outputs.image_exists == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.project }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:${{ steps.set-revision.outputs.target_revision }}
          target: ${{ matrix.project }}

      - name: Build and Push Docker Image If Changed
        if: steps.check-image.outputs.image_exists == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.project }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:${{ steps.set-revision.outputs.target_revision }}
          target: ${{ matrix.project }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:${{ steps.set-revision.outputs.target_revision }}
